version: '3.8'
services:
  ros_yolo8:
    build: 
      context: . # Dockerfileのあるディレクトリ
      dockerfile: Dockerfile # Dockerfileの名前
    image: ros_yolo8_image:latest # イメージ名
    volumes:
      - ./:/root/work # ローカルのフォルダを/root/workにマウント
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # GPUを利用可能にするための環境変数
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # 使用するGPUの数
              capabilities: [gpu]
